/**
 * AiCorrection.js
 *
 * Stores feedback loops: when a signal's predicted outcome is verified,
 * we log the accuracy and what the AI got right/wrong to build a
 * self-improving prompt context for future signals.
 */
const mongoose = require('mongoose');

const aiCorrectionSchema = new mongoose.Schema({
    signalId:   { type: mongoose.Schema.Types.ObjectId, ref: 'TradeSignal', required: true },
    symbol:     { type: String, required: true, uppercase: true },
    action:     { type: String, enum: ['BUY', 'SELL', 'HOLD'] },

    // Predicted values
    predictedEntry:  { type: Number },
    predictedSL:     { type: Number },
    predictedTP:     { type: Number },
    predictedRR:     { type: Number },
    confidence:      { type: Number }, // 0-100

    // Actual outcome
    outcome:         { type: String, enum: ['win', 'loss', 'tp_hit', 'sl_hit', 'timeout', 'cancelled'], default: 'timeout' },
    actualExitPrice: { type: Number, default: null },
    realisedPnlPct:  { type: Number, default: null },  // % return on risk
    maxFavourableExcursion: { type: Number, default: null }, // best price reached
    maxAdverseExcursion:    { type: Number, default: null }, // worst price reached

    // Learning metadata
    holdingHours:    { type: Number, default: null },
    entryAccuracy:   { type: Number, default: null },  // 0-1: how close to predicted entry
    rrAchieved:      { type: Number, default: null },  // actual R/R achieved

    // AI notes (generated by self-learning pass)
    aiNote:          { type: String, default: '' },

    checkedAt:       { type: Date, default: Date.now },
}, { timestamps: true });

aiCorrectionSchema.index({ symbol: 1, outcome: 1 });
aiCorrectionSchema.index({ signalId: 1 }, { unique: true });

module.exports = mongoose.model('AiCorrection', aiCorrectionSchema);
