/**
 * DailyReport.js
 *
 * One document per day per mode (paper/live).
 * Generated by AutomationEngine at the user's configured daily report time.
 */
const mongoose = require('mongoose');

const dailyReportSchema = new mongoose.Schema({
    date:          { type: String, required: true },    // 'YYYY-MM-DD' IST
    mode:          { type: String, enum: ['paper', 'live'], required: true },

    // Summary stats
    totalCycles:   { type: Number, default: 0 },        // how many 30-min cycles ran
    totalTrades:   { type: Number, default: 0 },
    wins:          { type: Number, default: 0 },
    losses:        { type: Number, default: 0 },
    winRate:       { type: Number, default: 0 },        // %
    noTrades:      { type: Number, default: 0 },        // cycles that found no setup
    skipped:       { type: Number, default: 0 },        // skipped due to low balance

    // Financial
    totalPnl:       { type: Number, default: 0 },       // USD
    totalMarginUsed:{ type: Number, default: 0 },       // total margin deployed
    avgConfidence:  { type: Number, default: 0 },
    avgLeverage:    { type: Number, default: 0 },

    // Highlights
    bestTrade:   {
        symbol:  { type: String, default: null },
        pnl:     { type: Number, default: null },
        pnlPct:  { type: Number, default: null },
    },
    worstTrade:  {
        symbol:  { type: String, default: null },
        pnl:     { type: Number, default: null },
        pnlPct:  { type: Number, default: null },
    },

    // Wallet snapshot at end of day
    walletStart:  { type: Number, default: null },
    walletEnd:    { type: Number, default: null },

    // Notification sent?
    notified:     { type: Boolean, default: false },

}, { timestamps: true });

dailyReportSchema.index({ date: -1, mode: 1 }, { unique: true });

module.exports = mongoose.model('DailyReport', dailyReportSchema);
